@baseUrl = http://localhost:3333

POST {{baseUrl}}/trips
Content-Type: application/json
# Authorization: Bearer {{token}}
# Idempotency-Key: acsb1ad-50d5-4a0f-b0d1-61a64a0fee28

{
  "destination": "Campina Grande",
  "starts_at": "2026-01-01T10:00:00Z",
  "ends_at": "2026-01-10T18:00:00Z",
  "owner_name": "Edd Silva",
  "owner_email": "edd.silva@example.com",
  "emails_to_invite": [
    "edd.silva@example.com", 
    "may.silva@example.com"
    ]
}

###
GET {{baseUrl}}/trips/d0ed5dc3-fff8-4140-b347-4642623a4669/confirm
Content-Type: application/json
# Authorization: Bearer
###

GET {{baseUrl}}/participants/0c3f299b-a66a-4d09-8db9-41cefcc3b5a4/confirm
Content-Type: application/json


###
POST {{baseUrl}}/trips/c1127418-7700-466b-a1d6-d7f9e39bf659/activities
Content-Type: application/json
# Authorization: Bearer {{token}}
# Idempotency-Key: acsb1ad-50d5-4a0f-b0d1-61a64a0fee28

{
  "title": "Show",
  "occours_at": "2026-01-06T10:00:00Z"
}

###
GET {{baseUrl}}/trips/c1127418-7700-466b-a1d6-d7f9e39bf659/activities
Content-Type: application/json

###
POST {{baseUrl}}/trips/c1127418-7700-466b-a1d6-d7f9e39bf659/links
Content-Type: application/json
# Authorization: Bearer {{token}}
# Idempotency-Key: acsb1ad-50d5-4a0f-b0d1-61a64a0fee28

{
  "title": "Reserva do Airbnb",
  "url": "https://www.airbnb.com/rooms/12345678"
}